import {chromium} from 'playwright';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');fs.mkdirSync(path.join(root,'test-artifacts'),{recursive:true});const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const data={ok:true,systemd:[{name:'service-panel.service',active:'active',protected:true,ports:[80]}],docker:[{name:'test-container',image:'nginx:alpine',state:'running',status:'Up',ports:[8080]}],host:{name:'test',uptime:5000,memoryTotal:100,memoryUsed:20,load:1,cores:4},warnings:[]};
let sshInput='';await page.routeWebSocket('ws://panel.test/**',ws=>{ws.send(JSON.stringify({type:'ready',data:'已连接'}));ws.onMessage(raw=>{const m=JSON.parse(raw);if(m.type==='input'){sshInput+=m.data;ws.send(JSON.stringify({type:'data',data:Buffer.from(m.data).toString('base64')}))}})});
let saved=false,deploys=0,rules=[],updates=0,createdProjects=[],allowedPorts=[];
await page.route('http://panel.test/**',async route=>{const url=new URL(route.request().url());if(url.pathname==='/'||url.pathname.startsWith('/assets/')){const f=path.join(root,'public',url.pathname==='/'?'index.html':url.pathname);return route.fulfill({body:f.endsWith('.html')?fs.readFileSync(f,'utf8').replaceAll('{{APP_VERSION}}',JSON.parse(fs.readFileSync(path.join(root,'package.json'))).version):fs.readFileSync(f),contentType:f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'font/woff2'})}
let body=data;if(url.pathname==='/api/ssh/status')body={ok:true,enabled:true,username:'admin',port:22222};if(url.pathname==='/api/ssh/ticket')body={ok:true,ticket:'test-ticket'};const b=route.request().postDataJSON();if(url.pathname==='/api/compose')body={ok:true,projects:[{name:'demo',files:['/test/docker-compose.yaml']},...createdProjects]};if(url.pathname==='/api/compose/file')body={ok:true,file:'/test/docker-compose.yaml',content:'services:\n  app:\n    image: nginx:alpine\n',revision:'abc'};
if(url.pathname==='/api/compose/create'){createdProjects.push({name:b.project,files:['/test/'+b.project+'/compose.yaml']});body={ok:true,project:b.project}}
if(url.pathname==='/api/compose/save'){saved=true;body={ok:true,revision:'def',msg:'已保存'}}if(url.pathname==='/api/compose/validate')body={ok:true,msg:'校验通过'};if(url.pathname==='/api/compose/deploy'){deploys++;body={ok:true,job:'123'}}
if(url.pathname==='/api/firewall')body={ok:true,installed:true,active:true,protectedPorts:[80,22],rules,note:'默认放行，屏蔽覆盖 Docker 端口'};
if(url.pathname==='/api/firewall/scan')body={ok:true,scannedAt:Date.now(),warnings:[],ports:[{port:'18080',protocol:'tcp',addresses:['0.0.0.0','::'],services:['Docker · demo-web → 80/tcp'],state:'default',localOnly:false},{port:'15353',protocol:'udp',addresses:['0.0.0.0'],services:['系统服务 · dns.service'],state:'deny',localOnly:false},{port:'19000',protocol:'tcp',addresses:['127.0.0.1'],services:['系统服务 · local.service'],state:'default',localOnly:true}]};
if(url.pathname==='/api/firewall/allow-scanned'){allowedPorts=b.ports;rules=b.ports.map((p,i)=>({...p,id:'scan-'+i,action:'allow',note:'Docker · demo-web'}));body={ok:true,msg:'已记录放行与备注'}}
if(url.pathname==='/api/firewall/rule'){rules=[{...b,id:'test'}];body={ok:true}}if(url.pathname==='/api/firewall/delete'){rules=[];body={ok:true}}
if(url.pathname==='/api/traffic')body={ok:true,period:url.searchParams.get('period'),since:Date.now()-3600000,lastSample:Date.now(),entities:[{id:'nic:eth0',label:'eth0',kind:'nic',rx:2048,tx:4096,rxRate:100,txRate:200,available:true},{id:'systemd:demo',label:'demo.service',kind:'systemd',rx:1024,tx:2048,available:true},{id:'docker:host',label:'host-container',kind:'docker',rx:0,tx:0,available:false,note:'共享主机网络，无法独立归属'}],series:[{time:Date.now(),rx:2048,tx:4096}],note:'每 60 秒采样'};
if(url.pathname==='/api/maintenance/update-sources'){updates++;body={ok:true,job:'123'}}if(url.pathname.startsWith('/api/jobs/'))body={ok:true,label:'测试任务',state:'done',result:'完成',log:'测试输出'};if(url.pathname==='/api/jobs')body={ok:true,jobs:[]};await route.fulfill({json:body});});
await page.goto('http://panel.test');await page.locator('#app').waitFor({state:'visible'});assert.equal(await page.locator('[data-favorite], [data-view="favorites"]').count(),0);
await page.locator('[data-view="docker"]').first().click();await page.locator('[data-view="compose"]').click();await page.locator('#compose-content').waitFor();await page.waitForFunction(()=>!document.querySelector('#compose-save').disabled);await page.locator('#compose-content').fill('services:\n  app:\n    image: nginx:latest\n');await page.locator('#compose-save').click();await page.waitForFunction(()=>document.querySelector('#ops-message').textContent.includes('已保存'));assert(saved);assert.equal(deploys,0);await page.locator('#compose-deploy').click();await page.locator('#job-dialog').waitFor({state:'visible'});assert.equal(deploys,1);await page.locator('#job-close').click();
await page.locator('#compose-new').click();await page.locator('#compose-new-name').fill('new-app');await page.locator('#compose-new-form button[value="save"]').click();await page.waitForFunction(()=>document.querySelector('#compose-project')?.value==='new-app');assert.equal(deploys,1);
await page.locator('#compose-new').click();await page.locator('#compose-new-name').fill('deployed-app');await page.locator('#compose-new-form button[value="deploy"]').click();await page.locator('#job-dialog').waitFor({state:'visible'});await page.locator('#job-close').click();await page.waitForFunction(()=>document.querySelector('#compose-project')?.value==='deployed-app');assert.equal(deploys,2);
await page.locator('[data-view="firewall"]').click();await page.locator('#firewall-port').fill('18080');await page.locator('#firewall-action').selectOption('deny');await page.locator('#firewall-submit').click();await page.locator('[data-rule-delete]').waitFor();assert.equal(rules[0].action,'deny');await page.locator('[data-rule-delete]').click();await page.waitForFunction(()=>!document.querySelector('[data-rule-delete]'));
await page.locator('#firewall-scan').click();await page.locator('[data-scan-select="0"]').waitFor();assert(await page.locator('[data-scan-select="2"]').isDisabled());await page.locator('#firewall-scan-search').fill('demo-web');assert.equal(await page.locator('[data-scan-row]:visible').count(),1);await page.locator('#firewall-select-all').click();assert.equal(await page.locator('[data-scan-select]:checked').count(),1);await page.locator('#firewall-scan-search').fill('');await page.locator('#firewall-select-all').click();assert.equal(await page.locator('[data-scan-select]:checked').count(),2);await page.locator('#firewall-allow-selected').click();await page.waitForFunction(()=>document.querySelector('[data-rule-delete]'));assert.equal(allowedPorts.length,2);await page.locator('[data-scan-allow="0"]').waitFor();await page.locator('[data-scan-allow="0"]').click();await page.waitForFunction(()=>document.querySelectorAll('[data-rule-delete]').length===1);assert.equal(allowedPorts.length,1);
for(const width of [320,390,490,768,800,1024,1280,1920]){await page.setViewportSize({width,height:900});for(const view of ['all','systemd','docker','compose','firewall','traffic','ssh','activity']){if(view==='compose')await page.locator('[data-view="docker"]').first().click();await page.locator(`[data-view="${view}"]`).first().click();if(view==='compose')await page.waitForFunction(()=>document.querySelector('#compose-content')&&!document.querySelector('#compose-content').disabled);if(view==='firewall'){await page.locator('#firewall-form').waitFor();await page.locator('#firewall-scan').click();await page.locator('[data-scan-select]').first().waitFor();}if(view==='ssh'){await page.locator('#ssh-password').fill('test-password-only');await page.locator('#ssh-connect').click();await page.waitForFunction(()=>document.querySelector('#ssh-state')?.textContent==='已连接');await page.locator('[data-ssh-key="ctrl-c"]').click();}if(view==='traffic')await page.locator('#traffic-data table').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width} ${view}`);if(view==='all'){await page.locator('#overview-traffic-data .traffic-summary').waitFor();assert.equal(await page.locator('#overview-traffic-data b').last().textContent(),'6 KB');assert(await page.locator('#refresh-btn').evaluate(e=>e.getBoundingClientRect().height<50),'refresh label wraps');}if(width===390||width===1280)await page.screenshot({path:path.join(root,'test-artifacts',`ui-${view}-${width}.png`),fullPage:true});}}
await page.locator('[data-view="traffic"]').click();await page.locator('#traffic-kind').selectOption('docker');await page.waitForFunction(()=>document.querySelector('#traffic-data').textContent.includes('host-container'));assert.equal(await page.locator('#traffic-data .traffic-summary b').first().textContent(),'—');await page.locator('#traffic-period').selectOption('30d');await page.locator('[data-view="all"]').click();await page.locator('#update-sources').click();await page.locator('#job-dialog').waitFor({state:'visible'});assert.equal(updates,1);await page.locator('#job-close').click();await page.locator('#tasks-btn').click();await page.locator('#job-dialog').waitFor({state:'visible'});assert(sshInput.includes('\x03'));assert.deepEqual(errors,[]);console.log('PASS browser: 64 viewport/page combinations, Compose save/deploy separation, firewall forms, traffic periods/unavailable, jobs, no favorites, no JS errors');await browser.close();
