const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),vm=require('vm'),{EventEmitter}=require('events');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'panel-ops-test-')),composeFile=path.join(root,'compose.yaml');fs.writeFileSync(composeFile,'services:\n  web:\n    image: nginx:alpine\n');
const calls=[];let failValidate=false,scanFixture=false;function spawn(cmd,args){calls.push([cmd,args]);const c=new EventEmitter();c.stdout=new EventEmitter();c.stderr=new EventEmitter();c.kill=()=>{};process.nextTick(()=>{let out='',err='',code=0;if(cmd.endsWith('/docker')){if(args.includes('ls'))out=JSON.stringify([{Name:'demo',Status:'running',ConfigFiles:composeFile}]);else if(args[0]==='ps')out=scanFixture&&args.includes('-q')?'container-id':'';else if(args[0]==='inspect'&&scanFixture)out=JSON.stringify([{Id:'container-id',Name:'/demo-web',NetworkSettings:{Ports:{'80/tcp':[{HostPort:'18080',HostIp:'0.0.0.0'},{HostPort:'18080',HostIp:'::'}],'53/udp':[{HostPort:'15353',HostIp:'0.0.0.0'}]}}}]);else if(args.includes('config')&&failValidate){err='invalid compose';code=1}}if(cmd.endsWith('/ss'))out='LISTEN 0 128 0.0.0.0:2222 0.0.0.0:* users:(("sshd",pid=1,fd=1))';if(cmd.endsWith('/ss')&&args.includes('-H')&&scanFixture)out='tcp LISTEN 0 128 0.0.0.0:18080 0.0.0.0:* users:(("demo",pid=999999,fd=1))\nudp UNCONN 0 0 0.0.0.0:15353 0.0.0.0:*\ntcp LISTEN 0 128 127.0.0.1:19000 0.0.0.0:*\ntcp LISTEN 0 128 [::1]:19001 [::]:*';if(out)c.stdout.emit('data',out);if(err)c.stderr.emit('data',err);c.emit('close',code)});return c}
const context={module:{exports:{}},require:n=>n==='child_process'?{spawn}:n==='./platform'?require('../platform'):require(n),process,console,Buffer,setTimeout,clearTimeout,setInterval,clearInterval};vm.runInNewContext(fs.readFileSync(__dirname+'/../operations.js','utf8'),context);let response;
const ops=context.module.exports({root,send:(r,status,body)=>response={status,body},readBody:async req=>JSON.stringify(req.body),getProjects:async()=>({systemd:[],docker:[]}),invalidateProjects(){}});
async function api(url,body){await ops.route({method:body?'POST':'GET',body},{},new URL('http://test'+url));return response}
(async()=>{
 assert.throws(()=>ops.validateRule({port:'80',action:'deny',protocol:'tcp'},[80,22]));assert.throws(()=>ops.validateRule({port:'1:65535',action:'deny',protocol:'both'},[80]));assert.throws(()=>ops.validateRule({port:'8080;drop',action:'deny',protocol:'tcp'},[]));assert.throws(()=>ops.validateRule({port:'65536',action:'allow',protocol:'tcp'},[]));
 const rules=[{id:'test',port:'8080:8085',protocol:'both',action:'deny'}];const nft=ops.nftProgram(rules);assert(nft.includes('priority -110'));assert(nft.includes('tcp dport 8080-8085'));assert(nft.includes('udp dport 8080-8085'));assert(!nft.includes('flush ruleset'));assert(nft.includes('fib daddr type local'));
 assert.equal((await api('/api/firewall/rule',{port:'2222',protocol:'tcp',action:'deny'})).status,400);assert.equal((await api('/api/firewall/rule',{port:'18080',protocol:'tcp',action:'deny'})).status,200);assert.equal((await api('/api/firewall/rule',{port:'18079:18081',protocol:'tcp',action:'allow'})).status,400);assert.equal((await api('/api/firewall/rule',{port:'18080',protocol:'tcp',action:'allow'})).status,200);
 scanFixture=true;const scan=(await api('/api/firewall/scan')).body;assert.equal(scan.ports.length,4);assert(scan.ports.find(p=>p.port==='18080').services.some(n=>n.includes('demo-web')));assert.equal(scan.ports.find(p=>p.port==='19000').localOnly,true);assert.equal(scan.ports.find(p=>p.port==='19001').localOnly,true);assert.equal(scan.ports.find(p=>p.port==='15353').protocol,'udp');
 const split=ops.allowScanned([{id:'range',port:'18079:18081',protocol:'both',action:'deny'}],[{port:'18080',protocol:'tcp',services:['Docker · demo-web']}]);assert.equal(split.length,4);assert(split.some(r=>r.port==='18079:18081'&&r.protocol==='udp'&&r.action==='deny'));assert(split.some(r=>r.port==='18079'&&r.protocol==='tcp'&&r.action==='deny'));assert(split.some(r=>r.port==='18081'&&r.protocol==='tcp'&&r.action==='deny'));assert(split.some(r=>r.port==='18080'&&r.action==='allow'&&r.note.includes('demo-web')));
 assert.equal((await api('/api/firewall/allow-scanned',{ports:[{port:'19000',protocol:'tcp'}]})).status,400);assert.equal((await api('/api/firewall/allow-scanned',{ports:[{port:'9999',protocol:'tcp'}]})).status,400);assert.equal((await api('/api/firewall/allow-scanned',{ports:[]})).status,400);
 assert.equal((await api('/api/firewall/allow-scanned',{ports:[{port:'18080',protocol:'tcp'},{port:'15353',protocol:'udp'}]})).status,200);const persisted=JSON.parse(fs.readFileSync(path.join(root,'data/firewall.json')));assert(persisted.some(r=>r.port==='18080'&&r.note.includes('demo-web')));assert(persisted.some(r=>r.port==='15353'&&r.protocol==='udp'));scanFixture=false;
 assert.equal((await api('/api/compose')).body.projects.length,1);let original=(await api('/api/compose/file?project=demo&index=0')).body;
 assert.equal((await api('/api/compose/save',{project:'demo',index:0,revision:'stale',content:'x'})).status,409);
 failValidate=true;assert.equal((await api('/api/compose/save',{project:'demo',index:0,revision:original.revision,content:'broken'})).status,400);assert.equal(fs.readFileSync(composeFile,'utf8'),original.content);
 failValidate=false;const content='services:\n  web:\n    image: nginx:latest\n';const saved=await api('/api/compose/save',{project:'demo',index:0,revision:original.revision,content});assert.equal(saved.status,200);assert.equal(fs.readFileSync(composeFile,'utf8'),content);assert.equal(fs.readdirSync(path.join(root,'data/compose-backups')).length,1);assert(!calls.some(([,a])=>a.includes('up')));
 assert.equal((await api('/api/compose/deploy',{project:'demo'})).status,400);assert.equal((await api('/api/compose/deploy',{project:'demo',confirm:true})).status,202);await new Promise(r=>setTimeout(r,20));assert(calls.some(([,a])=>a.includes('up')&&a.includes('-d')));
 assert.equal((await api('/api/compose/create',{project:'../escape',content})).status,400);
 assert.equal((await api('/api/compose/create',{project:'demo',content})).status,409);
 failValidate=true;assert.equal((await api('/api/compose/create',{project:'new-app',content:'broken'})).status,400);assert(!fs.existsSync(path.join(root,'data/compose/new-app')));failValidate=false;
 const ups=calls.filter(([,a])=>a.includes('up')).length;
 assert.equal((await api('/api/compose/create',{project:'new-app',content})).status,201);assert.equal(calls.filter(([,a])=>a.includes('up')).length,ups);
 assert((await api('/api/compose')).body.projects.some(p=>p.name==='new-app'));assert.equal((await api('/api/compose/file?project=new-app')).body.content,content);assert.equal((await api('/api/compose/create',{project:'new-app',content})).status,409);
 assert.equal((await api('/api/compose/deploy',{project:'new-app',confirm:true})).status,202);await new Promise(r=>setTimeout(r,20));assert.equal(calls.filter(([,a])=>a.includes('up')).length,ups+1);
 ops.record('nic:test','test','nic','boot1',1000,2000);ops.record('nic:test','test','nic','boot1',1500,2700);let stat=ops.trafficView('24h').entities.find(e=>e.id==='nic:test');assert.equal(stat.rx,500);assert.equal(stat.tx,700);ops.record('nic:test','test','nic','boot2',1,1);stat=ops.trafficView('total').entities.find(e=>e.id==='nic:test');assert.equal(stat.rx,500);ops.record('docker:host','host','docker','id',0,0,false,'unsupported');assert.equal(ops.trafficView('7d').entities.find(e=>e.id==='docker:host').available,false);
 console.log('PASS Compose validation/conflict/backup, no implicit deploy, firewall scope/protected ports/overlap, traffic delta/reboot/unavailable');
})().catch(e=>{console.error(e);process.exitCode=1});
